name: Pull and Run Continer
on:
  push:
    branches: [ 'main' ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: davidkuk/helloworld:1.17

    steps:
      - name: Run docker continer
        run: echo "end"
        #uses: docker://davidkuk/helloworld:1.17
        #uses: docker://hello-world:latest
        #with:
        #  options: --workdir="/go_app"
