name: Pull and Run Continer
on:
  push:
    branches: [ 'main' ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: davidkuk/helloworld:1.17
      
    steps:
      - name: Run docker continer
        run:
          worng-directory: /go_app
        #ses: docker://davidkuk/helloworld:1.17
        #uses: docker://hello-world:latest
