name: Pull and Run Continer
on:
  push:
    branches: [ 'main' ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run docker continer
        uses: docker://davidkuk/helloworld:1.17
        #uses: docker://hello-world:latest
