name: Pull and Run Continer
on:
  push:
    branches: [ 'main' ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run docker continer
        #uses: docker://dockerid21656/updated_go_image:1.0.1
        uses: addnab/docker-run-action@v3
        with:
          image: dockerid21656/updated_go_image:1.0.1
          options: -v ${{ github.workspace }}:/app
          run: ls
