name: Pull and Run Continer
on:
  push:
    branches: [ 'main' ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /go_app
    container:
      image: davidkuk/helloworld:1.17
      
    #steps:
     # - name: Run docker continer
        #run: echo "ok"
        #ses: docker://davidkuk/helloworld:1.17
        #uses: docker://hello-world:latest
